site_name: 2018 CICESE Metatranscriptomics workshop 
site_url: https://ngs-docs.github.io/2018-cicese-metatranscriptomics
repo_name: 2018-cicese-metatranscriptomics
repo_url: https://github.com/ngs-docs/2018-cicese-metatranscriptomics
edit_uri: ""

copyright: 'Copyright &copy; 2018 <a href="http://ivory.idyll.org/lab/">Lab for Data Intensive Biology</a> at UC Davis'

# change directory names here
docs_dir: docs
site_dir: site

theme:

  # the next 2 lines are required to use the DIB version
  name: null
  custom_dir: 'mkdocs-material-dib/material'

  # pretty colors! see https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
  palette:
    primary: 'teal'
    accent: 'teal'
  
  # fun logos! see https://material.io/icons/
  logo:
    icon: 'dns'

  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# this will add docs/css/custom.css to all your docs
extra_css:
  - css/custom.css

# give a title for each page
nav:
  - 'Overview':
      - 'Welcome': 'welcome.md'
      - 'Schedule' : 'index.md'
      - 'Code of Conduct': 'code-of-conduct.md'

  - 'Day 1':
      - 'Cluster login': 'cicese-cluster.md'
      - 'Bioconda': 'working-with-bioconda.md'
      - 'TARA Sample Data': 'tara-sample-data.md'
      - 'Read QC': 'short-read-quality-control.md'
      - 'Error Trimming': 'khmer-trimming.md'
      - 'Assembly': 'metatranscriptome-assembly.md'
      - 'Evaluation': 'metatranscriptome-evaluation.md'
      - 'Count Transcriptomes': 'count_transcriptomes.md'

  - 'Day 2':
     - 'Annotation': 'metatranscriptome-annotation.md'
     - 'Mapping': 'read-mapping.md'
     - 'Taxonomic Classification': 'sourmash-taxonomic-classification.md'
     - 'Visualize with anvio': 'anvio.md'

