site_name: 2018 CICESE Metatranscriptomics workshop 
site_url: https://ngs-docs.github.io/2018-cicese-metatranscriptomics
repo_name: 2018-cicese-metatranscriptomics
repo_url: https://github.com/ngs-docs/2018-cicese-metatranscriptomics
edit_uri: ""

copyright: 'Copyright &copy; 2018 <a href="http://ivory.idyll.org/lab/">Lab for Data Intensive Biology</a> at UC Davis'

# change directory names here
docs_dir: docs
site_dir: site

theme:

  # the next 2 lines are required to use the DIB version
  name: null
  custom_dir: 'mkdocs-material-dib/material'

  # pretty colors! see https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
  palette:
    primary: 'teal'
    accent: 'teal'
  
  # fun logos! see https://material.io/icons/
  logo:
    icon: 'dns'

  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# this will add docs/css/custom.css to all your docs
extra_css:
  - css/custom.css

# give a title for each page
nav:
  - 'Overview':
      - 'Schedule' : 'index.md'
      - 'Code of Conduct': 'code-of-conduct.md'

  - 'Day 1':
      - 'Bienvenidos': 'welcome.md'
      - 'Cluster login': 'cicese-cluster.md'
      - 'Software setup': 'setting-up-tara-environment.md'
      - 'TARA Sample Data': 'tara-sample-data.md'
      - 'Short Read Quality Control': 'short-read-quality-control.md'
      - 'Sourmash Taxonomic Classification': 'sourmash-taxonomic-classification.md'
      - 'Comparing Samples': 'sample-comparison.md'

  - 'Day 2':
      - 'Khmer Error Trimming': 'khmer-trimming.md'
      - 'Assembly with Megahit': 'megahit-assembly.md'
      - 'Count Transcriptomes': 'count_transcriptomes.md'
      - 'Assembly Evaluation and Quantification': 'evaluation-and-mapping.md'
      - 'Assembly Annotation': 'annotation.md'
      - 'Filezilla': 'filezilla.md'
      - 'Bioconda': 'working-with-bioconda.md'
      - 'Workflows and Repeatability': 'automation-qc.md'

  - References:
     -  'References': 'references.md'

