samples: "tara_f5-20_TSRNA_samples.tsv"

basename: 'tara_f5-20'

data_directory: "/tara/data/TS_RNA"
#download_data: True
download_data: False

workflow: "assembly"
#workflow: "mapping"

#assembly_input:
#  assembly: "tara_f5-20_plass.fasta"
#  assembly_ext: "_plass"

trimmomatic:
  trim_cmd:  "ILLUMINACLIP:{}:2:40:15 LEADING:20 TRAILING:20 SLIDINGWINDOW:4:15 MINLEN:35"

  adapter_file:
    pe_name: "TruSeq3-PE.fa"
    pe_url: "https://raw.githubusercontent.com/timflutre/trimmomatic/master/adapters/TruSeq3-PE-2.fa"
    se_name: "TruSeq3-SE.fa"
    se_url: "https://raw.githubusercontent.com/timflutre/trimmomatic/master/adapters/TruSeq3-SE.fa"
